In [1]:
import numpy as np
import pandas as pd

In [2]:
books = pd.read_csv("data/Books.csv")
ratings = pd.read_csv("data/Ratings.csv")
users = pd.read_csv("data/Users.csv")

C:\Users\Acer\AppData\Local\Temp\ipykernel_820\1055836222.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("data/Books.csv")


In [3]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(271360, 8)
(1149780, 3)
(278858, 3)


In [4]:
books.head(2)

ISBN           Book-Title           Book-Author Year-Of-Publication  \
0  0195153448  Classical Mythology    Mark P. O. Morford                2002   
1  0002005018         Clara Callan  Richard Bruce Wright                2001   

                 Publisher                                        Image-URL-S  \
0  Oxford University Press  http://images.amazon.com/images/P/0195153448.0...   
1    HarperFlamingo Canada  http://images.amazon.com/images/P/0002005018.0...   

                                         Image-URL-M  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   

                                         Image-URL-L  
0  http://images.amazon.com/images/P/0195153448.0...  
1  http://images.amazon.com/images/P/0002005018.0...

In [5]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [6]:
books.rename(columns={
    "Book-Title": "title",
    "Book-Author": "author",
    "Year-Of-Publication": "year",
    "Publisher": "publisher"
}, inplace=True)

In [7]:
books.head(2)

ISBN                title                author  year  \
0  0195153448  Classical Mythology    Mark P. O. Morford  2002   
1  0002005018         Clara Callan  Richard Bruce Wright  2001   

                 publisher                                        Image-URL-S  \
0  Oxford University Press  http://images.amazon.com/images/P/0195153448.0...   
1    HarperFlamingo Canada  http://images.amazon.com/images/P/0002005018.0...   

                                         Image-URL-M  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   

                                         Image-URL-L  
0  http://images.amazon.com/images/P/0195153448.0...  
1  http://images.amazon.com/images/P/0002005018.0...

In [8]:
ratings.rename(columns={
    "User-ID": "user_id",
    "Book-Rating": "ratings",
}, inplace=True)

In [9]:
users.head(2)

User-ID                   Location   Age
0        1         nyc, new york, usa   NaN
1        2  stockton, california, usa  18.0

In [10]:
users.rename(columns={
    "User-ID": "user_id",
    "Location": "location",
    "Age": "age"
}, inplace=True)

In [11]:
users.head(2)

user_id                   location   age
0        1         nyc, new york, usa   NaN
1        2  stockton, california, usa  18.0

In [12]:
x = ratings['user_id'].value_counts() > 200
y = x[x].index

In [13]:
ratings = ratings[ratings['user_id'].isin(y)]

In [14]:
books_with_rating = books.merge(ratings, on='ISBN')

In [15]:
filtered_books = books_with_rating.groupby('title')['ratings'].count().reset_index()

In [16]:
filtered_books = filtered_books[filtered_books['ratings'] >= 50]

In [17]:
filtered_books.rename(columns={
    "ratings": "no_of_ratings"
}, inplace=True)

In [18]:
filtered_books

title  no_of_ratings
493                                                  1984             76
527                                   1st to Die: A Novel            162
664                                            2nd Chance            124
810                                             4 Blondes             71
1020                                84 Charing Cross Road             54
...                                                   ...            ...
159044                                    Year of Wonders             59
159277                                   You Belong To Me             56
159916  Zen and the Art of Motorcycle Maintenance: An ...             64
160067                                               Zoya             59
160158                                \O\" Is for Outlaw"            105

[742 rows x 2 columns]

In [19]:
final = books_with_rating.merge(filtered_books, on='title')
final

ISBN                              title              author  \
0      0399135782             The Kitchen God's Wife             Amy Tan   
1      0399135782             The Kitchen God's Wife             Amy Tan   
2      0399135782             The Kitchen God's Wife             Amy Tan   
3      0399135782             The Kitchen God's Wife             Amy Tan   
4      0399135782             The Kitchen God's Wife             Amy Tan   
...           ...                                ...                 ...   
61848  0743418131  Deck the Halls (Holiday Classics)  Mary Higgins Clark   
61849  0743418131  Deck the Halls (Holiday Classics)  Mary Higgins Clark   
61850  0743418131  Deck the Halls (Holiday Classics)  Mary Higgins Clark   
61851  0743418131  Deck the Halls (Holiday Classics)  Mary Higgins Clark   
61852  0743418131  Deck the Halls (Holiday Classics)  Mary Higgins Clark   

       year         publisher  \
0      1991  Putnam Pub Group   
1      1991  Putnam Pub Group   
2      1991  Putnam Pub Group   
3      1991  Putnam Pub Group   
4      1991  Putnam Pub Group   
...     ...               ...   
61848  2002            Pocket   
61849  2002            Pocket   
61850  2002            Pocket   
61851  2002            Pocket   
61852  2002            Pocket   

                                             Image-URL-S  \
0      http://images.amazon.com/images/P/0399135782.0...   
1      http://images.amazon.com/images/P/0399135782.0...   
2      http://images.amazon.com/images/P/0399135782.0...   
3      http://images.amazon.com/images/P/0399135782.0...   
4      http://images.amazon.com/images/P/0399135782.0...   
...                                                  ...   
61848  http://images.amazon.com/images/P/0743418131.0...   
61849  http://images.amazon.com/images/P/0743418131.0...   
61850  http://images.amazon.com/images/P/0743418131.0...   
61851  http://images.amazon.com/images/P/0743418131.0...   
61852  http://images.amazon.com/images/P/0743418131.0...   

                                             Image-URL-M  \
0      http://images.amazon.com/images/P/0399135782.0...   
1      http://images.amazon.com/images/P/0399135782.0...   
2      http://images.amazon.com/images/P/0399135782.0...   
3      http://images.amazon.com/images/P/0399135782.0...   
4      http://images.amazon.com/images/P/0399135782.0...   
...                                                  ...   
61848  http://images.amazon.com/images/P/0743418131.0...   
61849  http://images.amazon.com/images/P/0743418131.0...   
61850  http://images.amazon.com/images/P/0743418131.0...   
61851  http://images.amazon.com/images/P/0743418131.0...   
61852  http://images.amazon.com/images/P/0743418131.0...   

                                             Image-URL-L  user_id  ratings  \
0      http://images.amazon.com/images/P/0399135782.0...    11676        9   
1      http://images.amazon.com/images/P/0399135782.0...    36836        0   
2      http://images.amazon.com/images/P/0399135782.0...    46398        9   
3      http://images.amazon.com/images/P/0399135782.0...   113270        0   
4      http://images.amazon.com/images/P/0399135782.0...   113519        0   
...                                                  ...      ...      ...   
61848  http://images.amazon.com/images/P/0743418131.0...   250184        0   
61849  http://images.amazon.com/images/P/0743418131.0...   256407        0   
61850  http://images.amazon.com/images/P/0743418131.0...   261829        0   
61851  http://images.amazon.com/images/P/0743418131.0...   264031        0   
61852  http://images.amazon.com/images/P/0743418131.0...   266226        0   

       no_of_ratings  
0                111  
1                111  
2                111  
3                111  
4                111  
...              ...  
61848             58  
61849             58  
61850             58  
61851             58  
61852             58  

[61853 rows x 11 columns]

In [20]:
final.drop_duplicates(['user_id','title'], inplace=True)

In [22]:
books_matrix = final.pivot_table(columns='user_id', index='title', values='ratings')
books_matrix.fillna(0, inplace=True)

In [23]:
from scipy.sparse import csr_matrix
sparse = csr_matrix(books_matrix)

In [24]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm='brute')

In [25]:
model.fit(sparse)

NearestNeighbors(algorithm='brute')

In [26]:
distances, suggestions = model.kneighbors(books_matrix.iloc[317, :].values.reshape(1,-1), n_neighbors=6)

In [27]:
distances

array([[ 0.        , 32.09361307, 32.43454948, 33.10589071, 33.51119216,
        33.58571125]])

In [28]:
for i in range(len(suggestions)):
    print(books_matrix.index[suggestions[i]])

Index(['Like Water for Chocolate: A Novel in Monthly Installments With Recipes, Romances and Home Remedies',
       'Exclusive', 'No Safe Place', 'The Temple of My Familiar',
       'A Civil Action', 'Jacob Have I Loved'],
      dtype='object', name='title')


In [31]:
books_matrix.index[222]

'GARDEN OF SHADOWS (Dollanger Saga (Paperback))'

In [32]:
np.where(books_matrix.index == "Harry Potter and the Chamber of Secrets (Book 2)")

(array([237], dtype=int64),)

In [62]:
def recommend_books(book_name):
    book_id = np.where(books_matrix.index == book_name)[0][0]
    distances, suggestions = model.kneighbors(books_matrix.iloc[book_id, :].values.reshape(1,-1), n_neighbors=6)
    
    data = []
    for i in range(len(suggestions[0])):
        item = []
        temp_df = books[books['title'] == books_matrix.index[suggestions[0]][i]]
        item.extend(list(temp_df.drop_duplicates('title')['title'].values))
        item.extend(list(temp_df.drop_duplicates('title')['author'].values))
        item.extend(list(temp_df.drop_duplicates('title')['Image-URL-M'].values))
        
        data.append(item)
    
    return data

In [65]:
recommend_books("Guilty Pleasures (Anita Blake Vampire Hunter (Paperback))")

[['Guilty Pleasures (Anita Blake Vampire Hunter (Paperback))',
  'Laurell K. Hamilton',
  'http://images.amazon.com/images/P/0441304834.01.MZZZZZZZ.jpg'],
 ['A Civil Action',
  'JONATHAN HARR',
  'http://images.amazon.com/images/P/0679772677.01.MZZZZZZZ.jpg'],
 ['Fatal Cure',
  'Robin Cook',
  'http://images.amazon.com/images/P/0425145638.01.MZZZZZZZ.jpg'],
 ["CAT'S EYE",
  'MARGARET ATWOOD',
  'http://images.amazon.com/images/P/0553282476.01.MZZZZZZZ.jpg'],
 ['Nothing Lasts Forever',
  'Sidney Sheldon',
  'http://images.amazon.com/images/P/0688084915.01.MZZZZZZZ.jpg'],
 ['No Safe Place',
  'RICHARD NORTH PATTERSON',
  'http://images.amazon.com/images/P/0345404777.01.MZZZZZZZ.jpg']]

In [149]:
distances

array([[ 0.        , 69.5413546 , 69.69935437, 72.74613392, 76.83098333,
        77.3369252 ]])

In [66]:
# books_matrix
# model
# books

In [33]:
import pickle
pickle.dump(books_matrix, open("artifacts/books_matrix.pkl", "wb"))
pickle.dump(model, open("artifacts/model.pkl", "wb"))
pickle.dump(final, open("artifacts/books.pkl", "wb"))